### ISSUE TITLE
Can't find the GStreamer development packages

### ISSUE THREAD

**Issue by abhishek1390** [RidgeRun/meta-ridgerun-legacy#3]
Hi,
We are trying to build the **gstd** recipe, 
we are getting the build dependency of gstreamer-1.0 and gstreamer-base-1.0, 
but the above dependency packages mentioned already built in our yocto build.

Please find the attached log file. 
[error.txt](https://github.com/RidgeRun/meta-ridgerun/files/1715523/error.txt)

**Comment by rrcarlosrodriguez** [comment]
Hi @abhishek1390 . It looks like GstD is not finding Gstreamer core, its weird if Gstreamer 1.0 was already built.
Could you please run the following commands to rebuild Gstreamer and GstD?

```
bitbake gstreamer1.0 -c cleansstate
bitbake gstd -c cleansstate
bitbake gstd -c build
```

Can you see if gstreamer1.0 is being built before gstd?
